import { useState, useEffect, useRef, useCallback } from "react";
import { createPortal } from "react-dom";
import {
  NoisyRule, RuleBreakdown, RuleBreakdownBucket, AlertSample,
  WazuhRuleDetail, RuleTrend, NinjaDevice,
} from "../../api/client";
import { api } from "../../api/client";
import SevBadge from "../SevBadge";

interface Props {
  data: NoisyRule[] | null;
  error: string | null;
  hoursBack: number;
}

type SortKey = "alert_count" | "level" | "rule_id";

const SEV_ORDER = ["critical", "high", "medium", "low"] as const;
const SEV_LABELS: Record<string, string> = {
  critical: "Critical", high: "High", medium: "Medium", low: "Low",
};
const SEV_BTN_ACTIVE: Record<string, string> = {
  critical: "bg-[#ff2d6d]/15 text-[#ff2d6d] border-[#ff2d6d]/45",
  high:     "bg-[#ff6b35]/15 text-[#ff6b35] border-[#ff6b35]/40",
  medium:   "bg-[#fbbf24]/15 text-[#fbbf24] border-[#fbbf24]/38",
  low:      "bg-[#34d399]/12 text-[#34d399] border-[#34d399]/30",
};
const SEV_DOT: Record<string, string> = {
  critical: "#ff2d6d", high: "#ff6b35", medium: "#fbbf24", low: "#34d399",
};

const TODAY = new Date().toISOString().split("T")[0];

// ── XML builder ───────────────────────────────────────────────────────────────

function xmlEscape(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildSuppressXml(ruleId: string, description: string, index = 0, notes = ""): string {
  const id = 100900 + index;
  const notesPart = notes.trim() ? ` - ${xmlEscape(notes.trim())}` : "";
  return `<rule id="${id}" level="0">
  <if_sid>${ruleId}</if_sid>
  <description>False positive - ${xmlEscape(description)}${notesPart} - suppressed ${TODAY}</description>
</rule>`;
}

// ── Helper functions ──────────────────────────────────────────────────────────

function describeRule(rule: NoisyRule, detail: WazuhRuleDetail | null): {
  text: string; category: string; categoryColor: string;
} {
  const groups   = detail?.groups ?? [];
  const filename = (detail?.filename ?? "").toLowerCase();

  let category = "";
  let categoryColor = "text-slate-400 bg-surface-700/60";

  if (filename.includes("syscheck") || groups.some(g => g.startsWith("syscheck"))) {
    category = "File Integrity (FIM)";  categoryColor = "text-yellow-400 bg-yellow-500/10 border-yellow-500/20";
  } else if (filename.includes("sysmon")) {
    category = "Sysmon Endpoint";       categoryColor = "text-cyan-400 bg-cyan-500/10 border-cyan-500/20";
  } else if (filename.includes("windows") || groups.some(g => g.includes("windows_event"))) {
    category = "Windows Event Log";     categoryColor = "text-blue-400 bg-blue-500/10 border-blue-500/20";
  } else if (groups.some(g => ["authentication","login","pam"].some(k => g.includes(k)))) {
    category = "Authentication";        categoryColor = "text-purple-400 bg-purple-500/10 border-purple-500/20";
  } else if (groups.some(g => ["web","apache","nginx","iis"].some(k => g.includes(k)))) {
    category = "Web Server";            categoryColor = "text-green-400 bg-green-500/10 border-green-500/20";
  } else if (groups.some(g => ["firewall","network","pf"].some(k => g.includes(k)))) {
    category = "Network / Firewall";    categoryColor = "text-red-400 bg-red-500/10 border-red-500/20";
  } else if (groups.some(g => g.includes("vulnerability_detector"))) {
    category = "Vulnerability Scanner"; categoryColor = "text-orange-400 bg-orange-500/10 border-orange-500/20";
  } else if (groups.some(g => g.includes("rootcheck") || g.includes("rootkit"))) {
    category = "Rootkit Detection";     categoryColor = "text-red-500 bg-red-500/10 border-red-500/20";
  } else if (filename.includes("osquery")) {
    category = "osquery";               categoryColor = "text-teal-400 bg-teal-500/10 border-teal-500/20";
  } else if (detail?.filename) {
    const base = detail.filename.replace(/^\d+-/, "").replace(/_rules\.xml$/, "").replace(/_/g, " ");
    category = base.charAt(0).toUpperCase() + base.slice(1);
  }

  const parts: string[] = [`Fires when: ${rule.description}.`];
  if (detail?.mitre.technique.length) {
    const tactics = [...new Set(detail.mitre.tactic)].join(", ");
    parts.push(`MITRE ATT&CK: ${detail.mitre.technique.slice(0, 2).join(", ")}${tactics ? ` (${tactics})` : ""}.`);
  }
  if (groups.some(g => g.includes("syscheck")))
    parts.push("Monitors file and registry changes on protected paths.");
  else if (groups.some(g => g.includes("vulnerability_detector")))
    parts.push("Generated by Wazuh's vulnerability detection module.");
  else if (groups.some(g => g.includes("rootcheck")))
    parts.push("Generated by Wazuh's rootkit detection engine.");

  return { text: parts.join(" "), category, categoryColor };
}

function findSimilarRules(current: NoisyRule, allRules: NoisyRule[]): NoisyRule[] {
  const stop = new Set(["alert","event","rule","found","detect","attempt",
    "file","user","host","system","windows","error","failed","successful","could"]);
  const words = current.description.toLowerCase().split(/\W+/)
    .filter(w => w.length > 3 && !stop.has(w));
  if (!words.length) return [];

  return allRules
    .filter(r => r.rule_id !== current.rule_id)
    .map(r => ({ r, score: words.filter(w => r.description.toLowerCase().includes(w)).length }))
    .filter(({ score }) => score >= 2)
    .sort((a, b) => b.score - a.score || b.r.alert_count - a.r.alert_count)
    .slice(0, 5)
    .map(({ r }) => r);
}

function matchNinja(agentName: string, devices: NinjaDevice[]): NinjaDevice | null {
  const norm = (s: string) => (s ?? "").toLowerCase().split(".")[0].trim();
  const t = norm(agentName);
  return devices.find(d => norm(d.systemName ?? "") === t || norm(d.displayName ?? "") === t) ?? null;
}

function computeConcentration(agents: RuleBreakdownBucket[], total: number) {
  let cum = 0, needed = 0;
  for (const a of agents) {
    cum += a.count; needed++;
    if (total > 0 && cum / total >= 0.9) break;
  }
  return { needed, pct: total > 0 ? Math.round((cum / total) * 100) : 0 };
}

// Collapse GUID segments (e.g. VSS snapshot paths) so near-identical paths are grouped
const GUID_RE = /\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\}/gi;
const HEX8_RE = /\\[0-9a-fA-F]{8,}(?=\\|$)/g;

function groupPaths(items: RuleBreakdownBucket[]): RuleBreakdownBucket[] {
  const map = new Map<string, number>();
  for (const item of items) {
    const key = item.value
      .replace(GUID_RE, "{GUID}")
      .replace(HEX8_RE, (m) => m.replace(/[0-9a-fA-F]{8,}/, "*"));
    map.set(key, (map.get(key) ?? 0) + item.count);
  }
  return Array.from(map.entries())
    .map(([value, count]) => ({ value, count }))
    .sort((a, b) => b.count - a.count);
}

// ── Heat color helper ─────────────────────────────────────────────────────────

function heatColor(pct: number): string {
  if (pct >= 75) return "#ff2d6d";
  if (pct >= 50) return "#ff6b35";
  if (pct >= 25) return "#fbbf24";
  return "#34d399";
}

// ── HourlyChart ───────────────────────────────────────────────────────────────

function HourlyChart({ data }: { data: { time: string; count: number }[] }) {
  if (!data.length) return null;
  const max = Math.max(...data.map(d => d.count), 1);
  return (
    <div className="flex items-end gap-px h-12 w-full">
      {data.map((d, i) => {
        const pct = (d.count / max) * 100;
        const h = new Date(d.time).getUTCHours();
        return (
          <div key={i} title={`${h}:00 — ${d.count}`} className="flex-1 rounded-sm"
            style={{
              height: `${Math.max(pct, d.count > 0 ? 8 : 2)}%`,
              background: d.count === 0 ? "#2d2b55" : `rgba(124,58,237,${0.22 + (pct / 100) * 0.75})`,
            }} />
        );
      })}
    </div>
  );
}

// ── DailyChart (7-day) ────────────────────────────────────────────────────────

function DailyChart({ data, trend }: {
  data: { date: string; count: number }[];
  trend: "up" | "down" | "flat";
}) {
  if (!data.length) return null;
  const max = Math.max(...data.map(d => d.count), 1);
  const avg = data.reduce((s, d) => s + d.count, 0) / data.length;
  const trendColor = trend === "up" ? "text-[#ff6b35]" : trend === "down" ? "text-[#34d399]" : "text-slate-400";
  const trendIcon  = trend === "up" ? "↑" : trend === "down" ? "↓" : "→";
  return (
    <div>
      <div className="flex items-end gap-1.5" style={{ height: 56 }}>
        {data.map((d, i) => {
          const pct = (d.count / max) * 100;
          const aboveAvg = d.count > avg * 1.1 && d.count > 0;
          return (
            <div key={i} className="flex-1 flex flex-col justify-end" style={{ height: "100%" }}>
              <div
                title={`${d.date}: ${d.count.toLocaleString()} alerts${aboveAvg ? " (above avg)" : ""}`}
                className="w-full rounded-sm"
                style={{
                  height: `${Math.max(pct, d.count > 0 ? 10 : 3)}%`,
                  background: d.count === 0
                    ? "#2d2b55"
                    : aboveAvg
                      ? `rgba(168,85,247,${0.6 + (pct / 100) * 0.4})`
                      : `rgba(124,58,237,${0.2 + (pct / 100) * 0.45})`,
                  boxShadow: aboveAvg ? "0 0 8px rgba(168,85,247,0.5)" : undefined,
                }}
              />
            </div>
          );
        })}
      </div>
      <div className="flex gap-1.5 mt-1">
        {data.map((d, i) => (
          <div key={i} className="flex-1 text-center">
            <span className="text-[9px] text-slate-600">
              {new Date(d.date + "T12:00:00Z").toLocaleDateString([], { weekday: "short" })}
            </span>
          </div>
        ))}
      </div>
      <div className={`flex items-center gap-1 mt-2 text-[11px] font-semibold ${trendColor}`}>
        <span>{trendIcon}</span>
        <span>{trend === "flat" ? "Stable volume" : `${trend === "up" ? "Increasing" : "Decreasing"} trend`}</span>
      </div>
    </div>
  );
}

// ── CopyButton ────────────────────────────────────────────────────────────────

function CopyButton({ text, label = "Copy XML", small = false, onCopy }: {
  text: string; label?: string; small?: boolean; onCopy?: () => void;
}) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={e => {
        e.stopPropagation();
        navigator.clipboard.writeText(text).then(() => {
          setCopied(true);
          onCopy?.();
          setTimeout(() => setCopied(false), 2000);
        });
      }}
      className={`flex items-center gap-1.5 font-medium border transition-colors shrink-0 ${
        small ? "text-[11px] px-2 py-1 rounded-lg" : "text-xs px-3 py-1.5 rounded-lg"
      } ${copied
        ? "bg-green-500/10 text-green-400 border-green-500/30"
        : "bg-surface-700 border-surface-500 text-slate-300 hover:bg-surface-600 hover:text-white"
      }`}
    >
      {copied
        ? <><svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" /></svg>Copied!</>
        : <><svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>{label}</>
      }
    </button>
  );
}

// ── MiniBarList ───────────────────────────────────────────────────────────────

function MiniBarList({ label, items, color = "bg-accent/60" }: {
  label: string; items: RuleBreakdownBucket[]; color?: string;
}) {
  if (!items.length) return null;
  const max = items[0].count;
  return (
    <div>
      <p className="text-[9px] font-semibold text-slate-600 uppercase tracking-widest mb-2">{label}</p>
      <div className="space-y-1.5">
        {items.slice(0, 8).map(b => (
          <div key={b.value} className="flex items-center gap-2">
            <div className="w-16 h-1.5 bg-surface-700 rounded-full overflow-hidden shrink-0">
              <div className={`h-full ${color} rounded-full`} style={{ width: `${(b.count / max) * 100}%` }} />
            </div>
            <span className="text-[11px] font-mono text-slate-300 truncate flex-1" title={b.value}>{b.value}</span>
            <span className="text-[11px] tabular-nums text-slate-500 shrink-0">{b.count.toLocaleString()}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── PathBarList (wrapping, grouped) ──────────────────────────────────────────

function PathBarList({ label, items, color = "bg-yellow-400/50" }: {
  label: string; items: RuleBreakdownBucket[]; color?: string;
}) {
  const grouped = groupPaths(items);
  if (!grouped.length) return null;
  const max = grouped[0].count;
  return (
    <div>
      <p className="text-[9px] font-semibold text-slate-600 uppercase tracking-widest mb-2.5">{label}</p>
      <div className="space-y-3">
        {grouped.slice(0, 8).map(b => (
          <div key={b.value}>
            <div className="flex items-center gap-2 mb-1">
              <div className="flex-1 h-1.5 bg-surface-700 rounded-full overflow-hidden">
                <div className={`h-full ${color} rounded-full`} style={{ width: `${(b.count / max) * 100}%` }} />
              </div>
              <span className="text-[11px] tabular-nums text-slate-500 shrink-0">{b.count.toLocaleString()}</span>
            </div>
            <span
              className="text-[11px] font-mono text-slate-300 leading-relaxed break-all select-all"
              title={b.value}
            >
              {b.value}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── ParsedMessage ─────────────────────────────────────────────────────────────

const MSG_KEY_COLOR: Record<string, string> = {
  Image: "text-cyan-400", TargetFilename: "text-yellow-400", TargetImage: "text-yellow-400",
  User: "text-purple-400", CommandLine: "text-orange-400", ParentImage: "text-slate-400",
  DestinationIp: "text-red-400", DestinationPort: "text-red-400", SourceIp: "text-red-300",
};
const MSG_SKIP = new Set(["ProcessGuid","ParentProcessGuid","CreationUtcTime",
  "ProcessId","ParentProcessId","EventRecordID","ThreadID","UtcTime","RuleName"]);

function ParsedMessage({ message }: { message: string }) {
  const lines = message.trim().split(/\r?\n/);
  const heading = lines[0].replace(/:$/, "").trim();
  const pairs = lines.slice(1)
    .map(l => { const i = l.indexOf(":"); return i > -1 ? { key: l.slice(0, i).trim(), value: l.slice(i + 1).trim() } : null; })
    .filter((p): p is { key: string; value: string } => !!p?.key && !!p?.value && p.value !== "-" && !MSG_SKIP.has(p.key));
  return (
    <div>
      <p className="text-[10px] font-semibold text-accent mb-2">{heading}</p>
      <div className="space-y-1">
        {pairs.map(({ key, value }) => (
          <div key={key} className="flex gap-2 min-w-0 text-[11px]">
            <span className="text-slate-600 shrink-0 w-32 text-right">{key}</span>
            <span className={`font-mono break-all ${MSG_KEY_COLOR[key] ?? "text-slate-300"}`}>{value}</span>
          </div>
        ))}
        {!pairs.length && <span className="text-slate-600 text-[11px]">No parsed fields</span>}
      </div>
    </div>
  );
}

// ── Section heading ───────────────────────────────────────────────────────────

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2 mb-3">
      <div className="w-0.5 h-3.5 rounded-full shrink-0" style={{ background: "linear-gradient(180deg, #7c3aed, #a855f7)" }} />
      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{children}</p>
    </div>
  );
}

// ── Quick Suppress Popover ────────────────────────────────────────────────────

function QuickSuppressPopover({ ruleId, description, alertCount, totalAlerts, onClose }: {
  ruleId: string; description: string; alertCount: number; totalAlerts: number; onClose: () => void;
}) {
  const xml = buildSuppressXml(ruleId, description);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const h = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) onClose(); };
    document.addEventListener("mousedown", h);
    return () => document.removeEventListener("mousedown", h);
  }, [onClose]);

  const handleCopy = () => {
    const reductionPct = totalAlerts > 0 ? (alertCount / totalAlerts) * 100 : undefined;
    api.addSuppressionLog({ rule_id: ruleId, description, alert_count: alertCount, reduction_pct: reductionPct, notes: undefined, total_alerts: totalAlerts }).catch(() => {});
  };

  return (
    <div ref={ref} onClick={e => e.stopPropagation()}
      className="absolute right-0 top-full mt-1 z-50 bg-surface-800 border border-surface-600 rounded-xl shadow-2xl p-4 w-96">
      <div className="flex items-center justify-between mb-3">
        <span className="text-[10px] font-semibold text-slate-500 uppercase tracking-widest">Suppression Rule</span>
        <button onClick={onClose} className="text-slate-600 hover:text-slate-300">
          <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <pre className="text-[11px] font-mono text-slate-300 bg-surface-900 rounded-lg border border-surface-700 p-3 leading-relaxed whitespace-pre overflow-x-auto mb-3">{xml}</pre>
      {totalAlerts > 0 && (
        <p className="text-[11px] text-slate-400 mb-3 leading-relaxed">
          Suppressing this rule will reduce your daily alerts by approximately{" "}
          <span className="text-[#34d399] font-semibold">{alertCount.toLocaleString()} alerts</span>
          {" "}(<span className="text-[#34d399] font-semibold">{((alertCount / totalAlerts) * 100).toFixed(1)}%</span> of total volume).
        </p>
      )}
      <div className="flex items-center gap-2">
        <CopyButton text={xml} onCopy={handleCopy} />
        <span className="text-[10px] text-slate-600">→ local_rules.xml</span>
      </div>
    </div>
  );
}

// ── Rule Side Drawer ──────────────────────────────────────────────────────────

function RuleDrawer({ rule, hoursBack, allRules, totalAlerts, onClose, zBase = 40 }: {
  rule: NoisyRule;
  hoursBack: number;
  allRules: NoisyRule[];
  totalAlerts: number;
  onClose: () => void;
  zBase?: number;
}) {
  const [breakdown, setBreakdown]     = useState<RuleBreakdown | null>(null);
  const [ruleDetail, setRuleDetail]   = useState<WazuhRuleDetail | null>(null);
  const [trend, setTrend]             = useState<RuleTrend | null>(null);
  const [ninjaDevs, setNinjaDevs]     = useState<NinjaDevice[]>([]);
  const [loading, setLoading]         = useState(true);
  const [notes, setNotes]             = useState("");
  const [xmlOpen, setXmlOpen]         = useState(false);

  useEffect(() => {
    setLoading(true);
    setBreakdown(null); setRuleDetail(null); setTrend(null);
    setNotes(""); setXmlOpen(false);
    Promise.all([
      api.wazuhRuleBreakdown(rule.rule_id, hoursBack),
      api.wazuhRuleDetail(rule.rule_id),
      api.wazuhRuleTrend(rule.rule_id),
      api.ninjaDevices().catch(() => []),
    ]).then(([bd, rd, tr, nd]) => {
      setBreakdown(bd);
      setRuleDetail(rd && Object.keys(rd).length > 0 ? rd : null);
      setTrend(tr);
      setNinjaDevs(nd);
    }).catch(() => {}).finally(() => setLoading(false));
  }, [rule.rule_id, hoursBack]);

  useEffect(() => {
    const h = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", h);
    return () => document.removeEventListener("keydown", h);
  }, [onClose]);

  const xml = buildSuppressXml(rule.rule_id, rule.description, 0, notes);
  const sample: AlertSample | null = breakdown?.sample_alerts?.[0] ?? null;
  const { text: detectText, category, categoryColor } = describeRule(rule, ruleDetail);
  const similarRules = findSimilarRules(rule, allRules);
  const rulePct = totalAlerts > 0 ? ((rule.alert_count / totalAlerts) * 100).toFixed(1) : null;
  const parentIds = ruleDetail?.if_sid?.trim()
    ? ruleDetail.if_sid.trim().split(/[\s,]+/).filter(Boolean)
    : [];

  // Agent concentration
  const concentration = breakdown
    ? computeConcentration(breakdown.top_agents, breakdown.total)
    : null;
  const isConcentrated = !!concentration && concentration.needed <= 2
    && breakdown!.top_agents.length >= 1 && breakdown!.total > 5;

  const drawer = (
    <>
      <div className="fixed inset-0 bg-black/30" style={{ zIndex: zBase }} onClick={onClose} />
      <div
        className="fixed inset-y-0 right-0 w-[680px] flex flex-col"
        style={{
          zIndex: zBase + 10,
          background: "linear-gradient(180deg, #1a1a3e 0%, #13132b 100%)",
          borderLeft: "1px solid #2d2b55",
          boxShadow: "-8px 0 48px rgba(0,0,0,0.8), -1px 0 0 rgba(124,58,237,0.25)",
          animation: "slideInRight 0.25s cubic-bezier(0.4, 0, 0.2, 1)",
        }}
      >

        {/* Header */}
        <div className="shrink-0 px-5 py-4 border-b border-surface-600">
          <div className="flex items-start justify-between gap-3">
            <div className="min-w-0 flex-1">
              <div className="flex items-center gap-2 mb-1 flex-wrap">
                <span className="font-mono text-sm text-accent font-semibold">Rule {rule.rule_id}</span>
                <SevBadge severity={rule.severity} label={`Level ${rule.level}`} />
                {category && (
                  <span className={`px-2 py-0.5 rounded-md text-[10px] font-semibold border ${categoryColor}`}>
                    {category}
                  </span>
                )}
              </div>
              <p className="text-sm font-semibold text-slate-200 leading-snug">{rule.description}</p>
              <p className="text-xs text-slate-500 mt-1">
                {rule.alert_count.toLocaleString()} alerts in last {hoursBack}h
                {rulePct && <span className="text-slate-600 ml-1.5">({rulePct}% of all alerts)</span>}
              </p>
            </div>
            <button onClick={onClose}
              className="p-1.5 rounded-lg text-slate-500 hover:text-white hover:bg-surface-700 transition-colors shrink-0 mt-0.5">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto">
          {loading ? (
            <div className="p-5 space-y-3">
              {[100, 60, 180, 80, 140, 100, 160].map((h, i) => (
                <div key={i} className="skeleton rounded-lg" style={{ height: h / 5 + 16 }} />
              ))}
            </div>
          ) : (
            <div className="divide-y divide-surface-800">

              {/* ── What This Detects ── */}
              <div className="px-5 py-4">
                <SectionLabel>What This Detects</SectionLabel>
                <p className="text-[12px] text-slate-300 leading-relaxed">{detectText}</p>
                {parentIds.length > 0 && (
                  <div className="flex items-center gap-2 mt-3">
                    <span className="text-[10px] text-slate-600">Parent rule{parentIds.length > 1 ? "s" : ""}:</span>
                    {parentIds.map(id => (
                      <span key={id} className="font-mono text-[10px] text-accent bg-accent/10 border border-accent/20 px-1.5 py-0.5 rounded">
                        {id}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              {/* ── Rule Details ── */}
              {ruleDetail && (
                <div className="px-5 py-4 space-y-4">
                  <SectionLabel>Rule Details</SectionLabel>

                  {/* Groups */}
                  {ruleDetail.groups.length > 0 && (
                    <div>
                      <p className="text-[9px] text-slate-700 mb-1.5">Groups</p>
                      <div className="flex flex-wrap gap-1">
                        {ruleDetail.groups.map(g => (
                          <span key={g} className="px-1.5 py-0.5 bg-surface-700 border border-surface-600 rounded text-[9px] font-mono text-slate-500">
                            {g}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* MITRE ATT&CK */}
                  {ruleDetail.mitre.id.length > 0 && (
                    <div className="bg-surface-800 rounded-xl border border-surface-700 p-3">
                      <p className="text-[9px] text-slate-600 mb-2">MITRE ATT&amp;CK</p>
                      <div className="space-y-2">
                        {ruleDetail.mitre.id.map((id, i) => (
                          <div key={id} className="flex items-start gap-3">
                            <a href={`https://attack.mitre.org/techniques/${id}/`}
                              target="_blank" rel="noreferrer"
                              onClick={e => e.stopPropagation()}
                              className="font-mono text-xs text-accent hover:text-white shrink-0 flex items-center gap-1">
                              {id}
                              <svg className="w-2.5 h-2.5 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                              </svg>
                            </a>
                            <div>
                              {ruleDetail.mitre.technique[i] && (
                                <p className="text-xs text-slate-300 font-medium">{ruleDetail.mitre.technique[i]}</p>
                              )}
                              {ruleDetail.mitre.tactic[i] && (
                                <p className="text-[10px] text-slate-600 capitalize">{ruleDetail.mitre.tactic[i]}</p>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Compliance */}
                  {(ruleDetail.pci_dss.length > 0 || ruleDetail.nist_800_53.length > 0 ||
                    ruleDetail.gdpr.length > 0 || ruleDetail.hipaa.length > 0 || ruleDetail.tsc.length > 0) && (
                    <div>
                      <p className="text-[9px] text-slate-700 mb-1.5">Compliance</p>
                      <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px]">
                        {ruleDetail.pci_dss.length > 0 && <span className="text-slate-500">PCI DSS <span className="text-slate-400">{ruleDetail.pci_dss.join(", ")}</span></span>}
                        {ruleDetail.nist_800_53.length > 0 && <span className="text-slate-500">NIST 800-53 <span className="text-slate-400">{ruleDetail.nist_800_53.join(", ")}</span></span>}
                        {ruleDetail.gdpr.length > 0 && <span className="text-slate-500">GDPR <span className="text-slate-400">{ruleDetail.gdpr.join(", ")}</span></span>}
                        {ruleDetail.hipaa.length > 0 && <span className="text-slate-500">HIPAA <span className="text-slate-400">{ruleDetail.hipaa.join(", ")}</span></span>}
                        {ruleDetail.tsc.length > 0 && <span className="text-slate-500">TSC <span className="text-slate-400">{ruleDetail.tsc.join(", ")}</span></span>}
                      </div>
                    </div>
                  )}

                  {/* Rule file */}
                  {ruleDetail.filename && (
                    <div className="flex items-center gap-2 text-[11px]">
                      <span className="text-slate-600">File:</span>
                      <span className="font-mono text-slate-400">{ruleDetail.filename}</span>
                      <a href={`https://github.com/wazuh/wazuh/blob/master/ruleset/rules/${ruleDetail.filename}`}
                        target="_blank" rel="noreferrer"
                        onClick={e => e.stopPropagation()}
                        className="text-accent hover:text-white flex items-center gap-0.5 ml-auto">
                        View source
                        <svg className="w-3 h-3 ml-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                          <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                        </svg>
                      </a>
                    </div>
                  )}
                </div>
              )}

              {/* ── Alert Patterns ── */}
              {breakdown && (
                <div className="px-5 py-4 space-y-4">
                  <div className="flex items-center justify-between">
                    <SectionLabel>Alert Patterns</SectionLabel>
                    {rulePct && (
                      <span className="text-[10px] text-slate-500">
                        <span className="text-accent font-semibold">{rulePct}%</span> of total alert volume
                      </span>
                    )}
                  </div>

                  {/* Top paths */}
                  {breakdown.top_syscheck_paths.length > 0 && (
                    <PathBarList label="Top Paths / Registry Keys" items={breakdown.top_syscheck_paths} color="bg-yellow-400/50" />
                  )}

                  {/* Top log sources/locations */}
                  {breakdown.top_locations.length > 0 && (
                    <MiniBarList label="Top Log Sources" items={breakdown.top_locations} color="bg-slate-400/40" />
                  )}

                  {/* Top users */}
                  {(breakdown.top_users.length > 0 || breakdown.top_srcusers.length > 0) && (
                    <MiniBarList
                      label="Top Users"
                      items={breakdown.top_users.length ? breakdown.top_users : breakdown.top_srcusers}
                      color="bg-purple-400/50"
                    />
                  )}

                  {/* Top processes (from trend data) */}
                  {trend && trend.top_processes.length > 0 && (
                    <MiniBarList label="Top Processes (7d)" items={trend.top_processes} color="bg-cyan-400/40" />
                  )}

                  {/* Event IDs */}
                  {breakdown.top_event_ids.length > 0 && (
                    <MiniBarList label="Windows Event IDs" items={breakdown.top_event_ids} color="bg-orange-400/50" />
                  )}

                  {/* 7-day trend */}
                  {trend && trend.daily.length > 0 && (
                    <div className="bg-surface-800 rounded-xl border border-surface-700 p-3">
                      <div className="flex items-center justify-between mb-3">
                        <p className="text-[9px] text-slate-600 uppercase tracking-widest font-semibold">7-Day Volume</p>
                        <div className="flex items-center gap-2 text-[10px]">
                          <span className="text-slate-600">Total:</span>
                          <span className="text-slate-300 font-semibold">{trend.total_7d.toLocaleString()}</span>
                          <span className="text-slate-600">· ~{Math.round(trend.total_7d / 7).toLocaleString()}/day</span>
                          {trend.trend_pct > 5 && (
                            <span className={`font-semibold ${trend.trend === "up" ? "text-orange-400" : "text-green-400"}`}>
                              {trend.trend === "up" ? "↑" : "↓"} {trend.trend_pct}%
                            </span>
                          )}
                        </div>
                      </div>
                      <DailyChart data={trend.daily} trend={trend.trend} />
                    </div>
                  )}

                  {/* 24h hourly */}
                  {breakdown.hourly_pattern.length > 0 && (
                    <div className="bg-surface-800 rounded-xl border border-surface-700 p-3">
                      <p className="text-[9px] text-slate-600 uppercase tracking-widest font-semibold mb-3">24h Distribution</p>
                      <HourlyChart data={breakdown.hourly_pattern} />
                      <div className="flex justify-between mt-1.5 text-[9px] text-slate-700">
                        <span>12am</span><span>6am</span><span>12pm</span><span>6pm</span><span>11pm</span>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* ── Affected Agents ── */}
              {breakdown && breakdown.top_agents.length > 0 && (
                <div className="px-5 py-4">
                  <SectionLabel>Affected Agents</SectionLabel>

                  {/* Concentration flag */}
                  {isConcentrated && (
                    <div className="flex items-start gap-2 mb-3 bg-amber-500/10 border border-amber-500/20 rounded-lg px-3 py-2">
                      <svg className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                      </svg>
                      <p className="text-[11px] text-amber-300 leading-snug">
                        <span className="font-semibold">Likely false positive:</span>{" "}
                        {concentration!.needed === 1 ? "1 machine is" : `${concentration!.needed} machines are`}{" "}
                        responsible for {concentration!.pct}% of these alerts. Suppression by hostname is probably safe.
                      </p>
                    </div>
                  )}

                  {/* Agent list with NinjaOne context */}
                  <div className="space-y-1.5">
                    {breakdown.top_agents.map((a, idx) => {
                      const ninja = ninjaDevs.length > 0 ? matchNinja(a.value, ninjaDevs) : null;
                      const pct   = breakdown.total > 0 ? Math.round((a.count / breakdown.total) * 100) : 0;
                      return (
                        <div key={a.value} className="bg-surface-800 border border-surface-700 rounded-lg px-3 py-2">
                          <div className="flex items-start justify-between gap-2">
                            <div className="min-w-0">
                              <div className="flex items-center gap-1.5">
                                <span className="text-xs font-mono font-semibold text-slate-200 truncate">{a.value}</span>
                                {ninja?.offline === false && (
                                  <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0" title="Online in NinjaOne" />
                                )}
                                {ninja?.offline === true && (
                                  <span className="w-1.5 h-1.5 rounded-full bg-slate-600 shrink-0" title="Offline in NinjaOne" />
                                )}
                              </div>
                              {ninja && (
                                <div className="flex flex-wrap gap-x-3 gap-y-0.5 mt-1 text-[10px]">
                                  {ninja.ipAddresses?.[0] && (
                                    <span className="text-slate-600">
                                      IP: <span className="text-slate-400 font-mono">{ninja.ipAddresses[0]}</span>
                                    </span>
                                  )}
                                  {ninja.os?.name && (
                                    <span className="text-slate-600">
                                      OS: <span className="text-slate-400">{ninja.os.name}</span>
                                    </span>
                                  )}
                                  {ninja.nodeClass && (
                                    <span className="text-slate-600">
                                      Role: <span className="text-slate-400">{ninja.nodeClass}</span>
                                    </span>
                                  )}
                                </div>
                              )}
                            </div>
                            <div className="text-right shrink-0">
                              <span className="text-xs font-semibold text-slate-200 tabular-nums">{a.count.toLocaleString()}</span>
                              <span className="text-[10px] text-slate-600 ml-1">({pct}%)</span>
                            </div>
                          </div>
                          <div className="mt-1.5 h-1 bg-surface-700 rounded-full overflow-hidden">
                            <div className="h-full bg-accent/50 rounded-full" style={{ width: `${pct}%` }} />
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* ── Recent Alert Sample ── */}
              {sample && (
                <div className="px-5 py-4">
                  <SectionLabel>Most Recent Alert Sample</SectionLabel>
                  <div className="bg-surface-800 border border-surface-700 rounded-xl p-3 space-y-1.5 text-[11px]">
                    {([
                      ["Time",     sample.timestamp ? new Date(sample.timestamp).toLocaleString() : null, "text-slate-400 font-mono"],
                      ["Agent",    sample.agent_name,   "text-slate-300 font-mono"],
                      ["Decoder",  sample.decoder,      "text-slate-400 font-mono"],
                      ["Location", sample.location,     "text-slate-400 font-mono break-all"],
                      ["Path",     sample.syscheck_path,"text-yellow-400 font-mono break-all"],
                      ["Event ID", sample.event_id,     "text-yellow-400 font-mono"],
                      ["User",     sample.user ?? sample.srcuser, "text-purple-400 font-mono"],
                      ["Src IP",   sample.src_ip,       "text-red-400 font-mono"],
                    ] as [string, string | null | undefined, string][])
                      .filter(([, v]) => v)
                      .map(([label, val, cls]) => (
                        <div key={label} className="flex gap-2">
                          <span className="text-slate-600 w-20 shrink-0 text-right">{label}</span>
                          <span className={cls}>{val}</span>
                        </div>
                      ))
                    }
                    {sample.syscheck_event && (
                      <div className="flex gap-2 mt-1">
                        <span className="text-slate-600 w-20 shrink-0 text-right">Change</span>
                        <span className={`px-2 py-0.5 rounded-full text-[10px] font-medium ${
                          sample.syscheck_event === "modified" ? "bg-yellow-500/20 text-yellow-400" :
                          sample.syscheck_event === "added"    ? "bg-green-500/20 text-green-400" :
                          sample.syscheck_event === "deleted"  ? "bg-red-500/20 text-red-400" :
                          "bg-surface-700 text-slate-400"
                        }`}>{sample.syscheck_event}</span>
                      </div>
                    )}
                    {sample.message && (
                      <div className="border-t border-surface-700 pt-3 mt-2">
                        <ParsedMessage message={sample.message} />
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* ── Related Rules ── */}
              {similarRules.length > 0 && (
                <div className="px-5 py-4">
                  <div className="flex items-center justify-between mb-2">
                    <SectionLabel>Related Rules in Your Environment</SectionLabel>
                  </div>
                  <p className="text-[10px] text-slate-600 mb-2.5">
                    Rules with similar alert patterns — also candidates for suppression review.
                  </p>
                  <div className="space-y-1.5">
                    {similarRules.map(r => (
                      <div key={r.rule_id} className="flex items-center gap-2 bg-surface-800 border border-surface-700 rounded-lg px-3 py-2">
                        <span className="font-mono text-[11px] text-accent shrink-0">{r.rule_id}</span>
                        <span className="text-[11px] text-slate-400 flex-1 truncate" title={r.description}>{r.description}</span>
                        <span className="text-[11px] tabular-nums text-slate-500 shrink-0">{r.alert_count.toLocaleString()}</span>
                        <SevBadge severity={r.severity} label={String(r.level)} />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* ── Suppress ── */}
              <div className="px-5 py-4">
                <SectionLabel>Suppression Rule</SectionLabel>

                {/* Notes field */}
                <div className="mb-3">
                  <label className="text-[10px] text-slate-600 block mb-1.5">
                    Reason / notes <span className="text-slate-700">(optional — included in rule description)</span>
                  </label>
                  <textarea
                    value={notes}
                    onChange={e => setNotes(e.target.value)}
                    placeholder="e.g. VSS Writer service activity on backup servers — confirmed benign"
                    rows={2}
                    className="w-full bg-surface-800 border border-surface-600 rounded-lg px-3 py-2 text-xs text-slate-300 placeholder-slate-600 focus:outline-none focus:border-accent/60 resize-none"
                  />
                </div>

                <div className="bg-surface-800 rounded-xl border border-surface-700 overflow-hidden">
                  <button
                    onClick={() => setXmlOpen(o => !o)}
                    className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-slate-300 hover:text-white hover:bg-surface-700/50 transition-colors"
                  >
                    <span className="flex items-center gap-2">
                      <svg className="w-4 h-4 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
                      </svg>
                      {xmlOpen ? "Hide XML" : "Show suppression XML"}
                    </span>
                    <span className={`text-slate-600 transition-transform ${xmlOpen ? "rotate-180" : ""}`}>▾</span>
                  </button>
                  {xmlOpen && (
                    <div className="border-t border-surface-700 p-4 bg-surface-900/50">
                      <pre className="text-[12px] font-mono text-slate-300 leading-relaxed whitespace-pre bg-black/30 rounded-lg border border-surface-700 p-3 mb-3 overflow-x-auto">{xml}</pre>
                      <div className="flex items-center gap-3">
                        <CopyButton text={xml} onCopy={() => {
                          const reductionPct = totalAlerts > 0 ? (rule.alert_count / totalAlerts) * 100 : undefined;
                          api.addSuppressionLog({ rule_id: rule.rule_id, description: rule.description, alert_count: rule.alert_count, reduction_pct: reductionPct, notes: notes.trim() || undefined, total_alerts: totalAlerts }).catch(() => {});
                        }} />
                        <p className="text-[10px] text-slate-600">
                          → <span className="font-mono">/var/ossec/etc/rules/local_rules.xml</span>
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              </div>

            </div>
          )}
        </div>
      </div>
    </>
  );

  return createPortal(drawer, document.body);
}

// ── Exported rule detail drawer (used from other tabs) ────────────────────────

export function RuleDetailDrawer({ ruleId, description = "", level = 0, hoursBack = 24, zBase = 60, onClose }: {
  ruleId: string;
  description?: string;
  level?: number;
  hoursBack?: number;
  zBase?: number;
  onClose: () => void;
}) {
  const [rule, setRule] = useState<NoisyRule>({
    rule_id: ruleId, description, level,
    severity: level >= 12 ? "critical" : level >= 8 ? "high" : level >= 4 ? "medium" : "low",
    alert_count: 0, last_triggered: "",
  });

  useEffect(() => {
    // Try to get accurate alert_count from noisy rules
    api.wazuhNoisyRules(hoursBack)
      .then(rules => { const found = rules.find(r => r.rule_id === ruleId); if (found) setRule(found); })
      .catch(() => {});
  }, [ruleId, hoursBack]);

  return <RuleDrawer rule={rule} hoursBack={hoursBack} allRules={[]} totalAlerts={0} zBase={zBase} onClose={onClose} />;
}

// ── Suppression Candidates Tab ────────────────────────────────────────────────

function SuppressTab({ allRules, checkedIds, onToggle, totalAlerts }: {
  allRules: NoisyRule[];
  checkedIds: Set<string>;
  onToggle: (id: string) => void;
  totalAlerts: number;
}) {
  const [xmlOut, setXmlOut] = useState<string | null>(null);
  const selected = allRules.filter(r => checkedIds.has(r.rule_id));

  const handleCopyAll = () => {
    selected.forEach(r => {
      const reductionPct = totalAlerts > 0 ? (r.alert_count / totalAlerts) * 100 : undefined;
      api.addSuppressionLog({ rule_id: r.rule_id, description: r.description, alert_count: r.alert_count, reduction_pct: reductionPct, notes: undefined, total_alerts: totalAlerts }).catch(() => {});
    });
  };

  const generateXml = () => {
    if (!selected.length) return;
    setXmlOut(selected.map((r, i) => buildSuppressXml(r.rule_id, r.description, i)).join("\n\n"));
  };

  return (
    <div className="space-y-4">
      {/* Action bar */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <p className="text-sm font-medium text-slate-300">
            {selected.length > 0
              ? `${selected.length} rule${selected.length !== 1 ? "s" : ""} selected for suppression`
              : "Check rules in the Noisy Rules tab to add them here"}
          </p>
          {selected.length > 0 && totalAlerts > 0 && (
            <p className="text-xs text-slate-500 mt-0.5">
              Est. alert reduction:{" "}
              <span className="text-accent font-semibold">
                {Math.round((selected.reduce((s, r) => s + r.alert_count, 0) / totalAlerts) * 100)}%
              </span>{" "}of current volume
            </p>
          )}
        </div>
        <button
          onClick={generateXml}
          disabled={!selected.length}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all
            text-white disabled:opacity-40 disabled:cursor-not-allowed"
          style={{ background: "linear-gradient(135deg, #7c3aed, #a855f7)", boxShadow: "0 0 20px rgba(124,58,237,0.4)" }}
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
          </svg>
          Generate suppression rules for selected
        </button>
      </div>

      {xmlOut && (
        <div className="bg-surface-800 rounded-xl border border-accent/20 overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 border-b border-surface-600">
            <span className="text-xs font-semibold text-slate-300">
              {selected.length} rule{selected.length !== 1 ? "s" : ""} · IDs {100900}–{100900 + selected.length - 1}
            </span>
            <CopyButton text={xmlOut} label="Copy all" onCopy={handleCopyAll} />
          </div>
          <pre className="text-[11px] font-mono text-slate-300 p-4 leading-relaxed whitespace-pre overflow-x-auto max-h-80">{xmlOut}</pre>
          <div className="px-4 py-2.5 border-t border-surface-600 bg-surface-900/40 text-[10px] text-slate-600">
            Paste into <span className="font-mono text-slate-500">/var/ossec/etc/rules/local_rules.xml</span>
          </div>
        </div>
      )}

      {allRules.length > 0 ? (
        <div className="bg-surface-800 rounded-xl border border-surface-600 overflow-hidden">
          <div className="flex items-center gap-3 px-4 py-3 border-b border-surface-600">
            <button onClick={() => allRules.forEach(r => { if (!checkedIds.has(r.rule_id)) onToggle(r.rule_id); })}
              className="text-xs text-accent hover:text-white font-medium transition-colors">Select all</button>
            <span className="text-slate-700">·</span>
            <button onClick={() => Array.from(checkedIds).forEach(id => onToggle(id))}
              className="text-xs text-slate-500 hover:text-slate-300 transition-colors">Clear all</button>
          </div>
          <div className="divide-y divide-surface-700/50">
            {allRules.map(r => {
              const pct = totalAlerts > 0 ? Math.round((r.alert_count / totalAlerts) * 100) : 0;
              const isChecked = checkedIds.has(r.rule_id);
              return (
                <label key={r.rule_id}
                  className={`flex items-center gap-3 px-4 py-3 cursor-pointer transition-colors border-l-2 ${
                    isChecked ? "bg-accent/5 border-accent" : "border-transparent hover:bg-surface-700/30"
                  }`}>
                  <input type="checkbox" checked={isChecked} onChange={() => onToggle(r.rule_id)}
                    className="w-4 h-4 rounded border-surface-500 bg-surface-700 text-accent focus:ring-0 shrink-0" />
                  <span className="font-mono text-xs text-accent shrink-0 w-14">{r.rule_id}</span>
                  <span className="text-sm text-slate-300 flex-1 truncate min-w-0" title={r.description}>{r.description}</span>
                  <SevBadge severity={r.severity} label={String(r.level)} />
                  <div className="flex items-center gap-1.5 shrink-0">
                    <span className="text-xs font-semibold text-slate-300 tabular-nums">{r.alert_count.toLocaleString()}</span>
                    {pct > 0 && <span className="text-[10px] text-slate-600">({pct}%)</span>}
                  </div>
                </label>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="text-slate-500 text-sm text-center py-12">No rules loaded</div>
      )}
    </div>
  );
}

// ── CSV export ────────────────────────────────────────────────────────────────

function exportRulesCSV(rules: NoisyRule[]) {
  const headers = ["Rule ID", "Description", "Severity", "Level", "Alert Count"];
  const rows = rules.map(r => [r.rule_id, r.description, r.severity, String(r.level), String(r.alert_count)]);
  const csv = [headers, ...rows].map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = "noisy_rules.csv"; a.click();
  URL.revokeObjectURL(url);
}

// ── Main component ────────────────────────────────────────────────────────────

export default function NoisyRules({ data, error, hoursBack }: Props) {
  const [activeTab, setActiveTab]   = useState<"rules" | "candidates">("rules");
  const [sortKey, setSortKey]       = useState<SortKey>("alert_count");
  const [sortDir, setSortDir]       = useState<"asc" | "desc">("desc");
  const [sevFilter, setSevFilter]   = useState<string>("");
  const [search, setSearch]         = useState("");
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const [drawerRule, setDrawerRule] = useState<NoisyRule | null>(null);
  const [quickSuppress, setQuickSuppress] = useState<string | null>(null);
  const [prevAlerts, setPrevAlerts] = useState<Map<string, number>>(new Map());

  // Fetch previous period data to compute trends (48h → prev period = 48h total minus 24h current)
  useEffect(() => {
    if (!data?.length) return;
    api.wazuhNoisyRules(hoursBack * 2).then(prevData => {
      const map = new Map<string, number>();
      for (const r of prevData) {
        const curCount = data.find(d => d.rule_id === r.rule_id)?.alert_count ?? 0;
        const prevCount = r.alert_count - curCount;
        if (prevCount > 0) map.set(r.rule_id, prevCount);
      }
      setPrevAlerts(map);
    }).catch(() => {});
  }, [data, hoursBack]);

  const handleSort = (key: SortKey) => {
    if (sortKey === key) setSortDir(d => d === "asc" ? "desc" : "asc");
    else { setSortKey(key); setSortDir("desc"); }
  };

  const toggleCheck = useCallback((id: string) => {
    setCheckedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }, []);

  const sevCounts = data
    ? SEV_ORDER.reduce((acc, s) => { acc[s] = data.filter(r => r.severity === s).length; return acc; }, {} as Record<string, number>)
    : null;

  const filtered = data
    ? [...data]
        .filter(r => !sevFilter || r.severity === sevFilter)
        .filter(r => !search.trim() || r.rule_id.includes(search.trim())
          || r.description.toLowerCase().includes(search.trim().toLowerCase()))
        .sort((a, b) => {
          const av = a[sortKey] ?? 0, bv = b[sortKey] ?? 0;
          const cmp = av < bv ? -1 : av > bv ? 1 : 0;
          return sortDir === "asc" ? cmp : -cmp;
        })
    : null;

  const totalAlerts = data?.reduce((s, r) => s + r.alert_count, 0) ?? 0;
  const maxCount    = filtered?.reduce((m, r) => Math.max(m, r.alert_count), 1) ?? 1;

  const SortIcon = ({ k }: { k: SortKey }) => (
    <span className={`ml-1 ${sortKey === k ? "text-accent" : "text-slate-600"}`}>
      {sortKey === k ? (sortDir === "asc" ? "↑" : "↓") : "↕"}
    </span>
  );

  const allVisibleChecked  = !!filtered?.length && filtered.every(r => checkedIds.has(r.rule_id));
  const someVisibleChecked = !!filtered?.some(r => checkedIds.has(r.rule_id));

  return (
    <div className="card">
      {/* Tab bar */}
      <div className="flex items-center gap-1 -mx-5 px-5 border-b border-surface-600 mb-5">
        {([
          ["rules",      "Noisy Rules"],
          ["candidates", `Suppression Candidates${checkedIds.size > 0 ? ` (${checkedIds.size})` : ""}`],
        ] as const).map(([tab, label]) => (
          <button key={tab} onClick={() => setActiveTab(tab)}
            className={`pb-3 pt-1 px-4 text-sm font-semibold border-b-2 transition-colors -mb-px whitespace-nowrap ${
              activeTab === tab ? "border-accent text-accent" : "border-transparent text-slate-500 hover:text-slate-300"
            }`}>
            {label}
          </button>
        ))}
      </div>

      {activeTab === "candidates" ? (
        <SuppressTab allRules={data ?? []} checkedIds={checkedIds} onToggle={toggleCheck} totalAlerts={totalAlerts} />
      ) : (
        <>
          {/* Controls */}
          <div className="flex flex-wrap items-center gap-3 mb-5">
            {/* Search */}
            <div className="relative flex-1 min-w-[200px]">
              <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
              </svg>
              <input type="text" value={search} onChange={e => setSearch(e.target.value)}
                placeholder="Search rule ID or description…"
                className="w-full pl-9 pr-8 py-2.5 bg-surface-700 border border-surface-600 rounded-lg text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:border-accent/60 transition-colors" />
              {search && (
                <button onClick={() => setSearch("")} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300">
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              )}
            </div>

            {/* Severity filters */}
            {sevCounts && (
              <div className="flex flex-wrap gap-2">
                <button onClick={() => setSevFilter("")}
                  className={`px-3.5 py-2 rounded-lg text-sm font-semibold border-2 transition-colors ${
                    !sevFilter ? "bg-accent/20 text-accent border-accent/40" : "text-slate-400 border-surface-600 hover:text-slate-200 hover:border-surface-500"
                  }`}>
                  All
                </button>
                {SEV_ORDER.map(sev => {
                  const count = sevCounts[sev];
                  if (sev !== "critical" && count === 0) return null;
                  const active = sevFilter === sev;
                  return (
                    <button key={sev} onClick={() => setSevFilter(active ? "" : sev)}
                      className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-sm font-semibold border-2 transition-colors ${
                        active ? SEV_BTN_ACTIVE[sev] : "text-slate-400 border-surface-600 hover:text-slate-200 hover:border-surface-500"
                      }`}>
                      <span className="w-2 h-2 rounded-full shrink-0" style={{ background: SEV_DOT[sev] }} />
                      {SEV_LABELS[sev]}
                      <span className="text-xs opacity-60">({count})</span>
                    </button>
                  );
                })}
              </div>
            )}
          </div>

          {/* CSV export */}
          {filtered && filtered.length > 0 && (
            <button
              onClick={() => exportRulesCSV(filtered)}
              className="flex items-center gap-1.5 px-3 py-2.5 rounded-lg text-xs font-medium text-slate-300 hover:text-white border border-surface-600 hover:border-surface-500 bg-surface-700 hover:bg-surface-600 transition-all shrink-0"
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Export CSV
            </button>
          )}

          {/* Subtitle */}
          <p className="text-xs text-slate-500 mb-4">
            Last {hoursBack}h
            {filtered && ` · ${filtered.length}${sevFilter ? ` ${sevFilter}` : ""} rule${filtered.length !== 1 ? "s" : ""}`}
            {search && ` matching "${search}"`}
            {checkedIds.size > 0 && <> · <span className="text-accent">{checkedIds.size} selected</span> — switch to Suppression Candidates to generate XML</>}
          </p>

          {error ? (
            <div className="text-red-400 text-sm py-6 text-center">{error}</div>
          ) : !filtered ? (
            <div className="space-y-2.5">{Array.from({ length: 8 }).map((_, i) => <div key={i} className="skeleton h-12 rounded-lg" />)}</div>
          ) : filtered.length === 0 ? (
            <div className="text-slate-500 text-sm text-center py-10">
              {search ? `No rules match "${search}"` : sevFilter ? `No ${sevFilter} rules` : "No rules found"}
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-surface-600">
                    <th className="py-3 px-3 w-10">
                      <input type="checkbox" checked={allVisibleChecked}
                        ref={el => { if (el) el.indeterminate = someVisibleChecked && !allVisibleChecked; }}
                        onChange={() => {
                          if (allVisibleChecked) filtered.forEach(r => { if (checkedIds.has(r.rule_id)) toggleCheck(r.rule_id); });
                          else filtered.forEach(r => { if (!checkedIds.has(r.rule_id)) toggleCheck(r.rule_id); });
                        }}
                        className="w-4 h-4 rounded border-surface-500 bg-surface-700 text-accent focus:ring-0 cursor-pointer" />
                    </th>
                    {([
                      ["rule_id",     "Rule ID"],
                      ["description", "Description"],
                      ["level",       "Severity"],
                      ["alert_count", "Alert Count"],
                    ] as [SortKey | "description", string][]).map(([key, label]) => (
                      <th key={key}
                        onClick={() => key !== "description" && handleSort(key as SortKey)}
                        className={`text-left py-3 px-3 text-xs font-semibold text-slate-400 whitespace-nowrap ${key !== "description" ? "cursor-pointer hover:text-slate-200" : ""}`}>
                        {label}{key !== "description" && <SortIcon k={key as SortKey} />}
                      </th>
                    ))}
                    <th className="py-3 px-3 w-14 text-center">
                      <span className="text-xs font-semibold text-slate-600">Trend</span>
                    </th>
                    <th className="py-3 px-3 w-28 text-right">
                      <span className="text-xs font-semibold text-slate-600">Suppress</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.map(rule => {
                    const pct = Math.round((rule.alert_count / maxCount) * 100);
                    const barColor   = heatColor(pct);
                    const isChecked  = checkedIds.has(rule.rule_id);
                    const isDrawer   = drawerRule?.rule_id === rule.rule_id;
                    const isQuick    = quickSuppress === rule.rule_id;
                    return (
                      <tr key={rule.rule_id}
                        className={`border-b border-surface-700/50 transition-colors ${
                          isDrawer ? "bg-accent/5" : isChecked ? "bg-surface-800/60" : "hover:bg-surface-700/30"
                        }`}>

                        <td className="py-3 px-3">
                          <input type="checkbox" checked={isChecked} onChange={() => toggleCheck(rule.rule_id)}
                            onClick={e => e.stopPropagation()}
                            className="w-4 h-4 rounded border-surface-500 bg-surface-700 text-accent focus:ring-0 cursor-pointer" />
                        </td>

                        <td className="py-3 px-3">
                          <button onClick={() => setDrawerRule(isDrawer ? null : rule)}
                            className="font-mono text-xs text-accent hover:text-white transition-colors flex items-center gap-1 group"
                            title="Open rule analysis">
                            {rule.rule_id}
                            <svg className={`w-3 h-3 text-slate-600 group-hover:text-accent transition-transform ${isDrawer ? "rotate-90" : ""}`}
                              fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                              <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                            </svg>
                          </button>
                        </td>

                        <td className="py-3 px-3 max-w-sm">
                          <button onClick={() => setDrawerRule(isDrawer ? null : rule)}
                            className="text-left truncate block text-slate-300 hover:text-white transition-colors w-full"
                            title={rule.description}>
                            {rule.description}
                          </button>
                        </td>

                        <td className="py-3 px-3">
                          <SevBadge severity={rule.severity} label={`${rule.level} · ${SEV_LABELS[rule.severity] ?? rule.severity}`} />
                        </td>

                        <td className="py-3 px-3">
                          <div className="flex items-center gap-2">
                            <div className="flex-1 h-1.5 bg-surface-600 rounded-full overflow-hidden min-w-[60px]">
                              <div className="h-full rounded-full" style={{ width: `${pct}%`, background: barColor }} />
                            </div>
                            <span className="font-semibold text-slate-200 tabular-nums min-w-[52px] text-right text-xs">
                              {rule.alert_count.toLocaleString()}
                            </span>
                          </div>
                        </td>

                        <td className="py-3 px-3 text-center w-14">
                          {(() => {
                            const prev = prevAlerts.get(rule.rule_id);
                            if (prev == null) return <span className="text-slate-700 text-xs">—</span>;
                            const pct = Math.round(((rule.alert_count - prev) / prev) * 100);
                            if (pct > 10) return (
                              <span className="text-[#ff6b35] text-base font-bold leading-none" title={`+${pct}% vs prev ${hoursBack}h`}>↑</span>
                            );
                            if (pct < -10) return (
                              <span className="text-[#34d399] text-base font-bold leading-none" title={`${pct}% vs prev ${hoursBack}h`}>↓</span>
                            );
                            return <span className="text-slate-500 text-xs" title={`${pct > 0 ? "+" : ""}${pct}% vs prev ${hoursBack}h`}>—</span>;
                          })()}
                        </td>

                        <td className="py-3 px-3 relative">
                          <button
                            onClick={e => { e.stopPropagation(); setQuickSuppress(prev => prev === rule.rule_id ? null : rule.rule_id); }}
                            className={`flex items-center gap-1.5 text-xs px-2.5 py-1.5 rounded-lg border transition-colors font-medium ${
                              isQuick ? "bg-accent/20 text-accent border-accent/30" : "text-slate-500 border-surface-600 hover:text-slate-200 hover:border-surface-500 hover:bg-surface-700"
                            }`}>
                            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                              <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
                            </svg>
                            Suppress
                          </button>
                          {isQuick && (
                            <QuickSuppressPopover ruleId={rule.rule_id} description={rule.description} alertCount={rule.alert_count} totalAlerts={totalAlerts} onClose={() => setQuickSuppress(null)} />
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {drawerRule && (
        <RuleDrawer
          rule={drawerRule}
          hoursBack={hoursBack}
          allRules={data ?? []}
          totalAlerts={totalAlerts}
          onClose={() => setDrawerRule(null)}
        />
      )}
    </div>
  );
}
